# Generated by Django 4.2.1 on 2023-05-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=1)),
                ('phno', models.CharField(max_length=12)),
                ('git', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('hrank', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=16)),
                ('addr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
