# Generated by Django 4.2.1 on 2023-05-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_certification_details_internship_delete_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='contact',
        ),
    ]
