# Generated by Django 4.2.1 on 2023-05-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.contact'),
        ),
        migrations.AddField(
            model_name='internship',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.contact'),
        ),
    ]
