# Generated by Django 4.2.1 on 2023-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contact_stdyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='adnum',
            field=models.CharField(default='exit', max_length=11),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
