# Generated by Django 4.2.1 on 2023-08-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_certi'),
    ]

    operations = [
        migrations.AddField(
            model_name='certi',
            name='adnum',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
