# Generated by Django 4.2.1 on 2023-08-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contact_image_contact_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='certi',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
