# Generated by Django 4.2.1 on 2023-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_certi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certi',
            name='credits',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certi',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
