# Generated by Django 5.0 on 2024-02-01 05:15

from django.db import migrations, models
from django.contrib.auth.models import User

class Migration(migrations.Migration):
    dependencies = [
        ('home', '0016_alter_certi_credits_alter_certi_score'),
    ]
    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certi_name', models.CharField(max_length=100)),
                ('drivelink', models.CharField(max_length=100)),
                ('certi_no', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('credits', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(User, on_delete=models.CASCADE)),
            ],
        ),
    ]
