# Generated by Django 5.0 on 2024-02-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_orders'),
    ]

    operations = [
    ]
